config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/destroy'

  get 'auth/:provider/callback', to: 'sessions#create' # , via: 'get'
  get 'auth/failure', to: redirect('/') # , via: 'get'
  get 'signout', to: 'sessions#destroy', as: 'signout' #, via: 'get'

  resources :project_updates

  get 'top/help', as: 'help'

  get 'auth/logout', as: 'logout'

  post 'auth/signup_check', as: 'signup_check'

  post 'auth/login_check', as: 'login_check'

  get 'auth/signup'

  get 'top/index'

  get 'auth/login', as: 'login'

  get 'auth/signup', as: 'signup'

  get 'user/list', as: 'user_list'

  get 'user/detail/:user_id' => 'user#detail', as: 'user_detail'

  get 'user/edit/:user_id' => 'user#edit', as: 'user_edit'

  get 'project/detail/:project_id' => 'project#detail', as: 'project_detail'

  get 'project/edit', as: 'project_edit'

  get 'project/create', as: 'project_create'

  get 'projects/join/:id', to: 'projects#join'

  get 'projects/leave/:id', to: 'projects#leave'

  get 'projects/posts/:id', to: 'projects#kakikomizu'

  get 'dashboard', to: 'dashboard#index'

  get 'feed' => 'top#feed'
  root 'dashboard#index', as: 'root'

  resources :projects
  resources :users

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/project_update.rb
class ProjectUpdate < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  has_many   :project_update_histories
  mount_uploader :comment_image, CommentImageUploader
end

app/controllers/project_updates_controller.rb
# coding: utf-8
class ProjectUpdatesController < ApplicationController
  include SnsPublisher
  before_action :set_project_update, only: [:show, :edit, :update, :destroy]

  # GET /project_updates/new
  def new
    @project_update = ProjectUpdate.new
  end

  # GET /project_updates/1/edit
  def edit
  end

  # POST /project_updates
  def create
    @project_update = ProjectUpdate.new(project_update_params)
    @project_update.user_id = @my_user.id

    if @project_update.save
      @project_update.project.send_mail_addresses.each do |m|
        ProjectMailer.tell_update(m, @project_update).deliver_later unless m == ''
      end

      @project_update.project.update!(
        last_commented_at: @project_update.created_at
      )
      project_publish_to_sns_page(
        "#{@my_user.name} さんが課題 #{@project_update.project.subject} にフォローを投稿しました。",
        @project_update.project,
        @my_user
      )

      redirect_to project_path(id: params[:project_update][:project_id]), notice: 'フォローを投稿しました。'
    else
      render :new
    end
  end

  # PATCH/PUT /project_updates/1
  def update
    unless @project_update.user_id == @my_user.id || @project_update.project.user_id == @my_user.id
      redirect_to project_path(id: params[:project_update][:project_id]), notice: 'フォローを修正できませんでした'
    end

    if @project_update.update(project_update_params)
      history = ProjectUpdateHistory.new(
        user_id: @my_user.id,
        project_update_id: @project_update.id
      )
      history.save
      redirect_to project_path(id: params[:project_update][:project_id]), notice: 'フォローを修正しました。'
    else
      render :edit
    end
  end

  # DELETE /project_updates/1
  def destroy
    @project_update.description = "( #{@my_user.name} さんが削除しました )"
    @project_update.comment_image = nil
    @project_update.freezing = true
    if @project_update.save
      history = ProjectUpdateHistory.new(
        user_id:           @my_user.id,
        project_update_id: @project_update.id
      )
      history.save
    end
    redirect_to project_path(id: @project_update.project_id), notice: 'フォローを削除しました。'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project_update
    @project_update = ProjectUpdate.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_update_params
    params.require(:project_update).permit(:project_id, :description, :comment_image)
  end
end

app/helpers/project_updates_helper.rb
module ProjectUpdatesHelper
end

app/views/project_updates/_form.html.erb
<%= form_for(@project_update) do |f| %>
  <% if @project_update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_update.errors.count, "error") %> prohibited this project_update from being saved:</h2>

      <ul>
        <% @project_update.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :project_id, value: params[:project_id] %>
  <div class="input_text">
    <%= f.text_area :description, class: 'form-control', rows: 10 %>
  </div>
  <button type="submit" class="btn btn-default btn-primary mt20" aria-label="Left Align">
    <%= t '.do_comment' %>
  </button>
<% end %>

app/views/project_updates/edit.html.erb
<div class="content">
  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <%= render 'form' %>
</div>

app/views/project_updates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Project Updates</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Description</th>
      <th>Delete flag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_updates.each do |project_update| %>
      <tr>
        <td><%= project_update.project_id %></td>
        <td><%= project_update.description %></td>
        <td><%= link_to 'Show', project_update %></td>
        <td><%= link_to 'Edit', edit_project_update_path(project_update) %></td>
        <td><%= link_to 'Destroy', project_update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project update', new_project_update_path %>

app/views/project_updates/new.html.erb
<div class="content">
  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <%= render 'form' %>
</div>

app/views/project_updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @project_update.project_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project_update.description %>
</p>

<%= link_to 'Edit', edit_project_update_path(@project_update) %> |
<%= link_to 'Back', project_updates_path %>