config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/destroy'

  get 'auth/:provider/callback', to: 'sessions#create' # , via: 'get'
  get 'auth/failure', to: redirect('/') # , via: 'get'
  get 'signout', to: 'sessions#destroy', as: 'signout' #, via: 'get'

  resources :project_updates

  get 'top/help', as: 'help'

  get 'auth/logout', as: 'logout'

  post 'auth/signup_check', as: 'signup_check'

  post 'auth/login_check', as: 'login_check'

  get 'auth/signup'

  get 'top/index'

  get 'auth/login', as: 'login'

  get 'auth/signup', as: 'signup'

  get 'user/list', as: 'user_list'

  get 'user/detail/:user_id' => 'user#detail', as: 'user_detail'

  get 'user/edit/:user_id' => 'user#edit', as: 'user_edit'

  get 'project/detail/:project_id' => 'project#detail', as: 'project_detail'

  get 'project/edit', as: 'project_edit'

  get 'project/create', as: 'project_create'

  get 'projects/join/:id', to: 'projects#join'

  get 'projects/leave/:id', to: 'projects#leave'

  get 'projects/posts/:id', to: 'projects#kakikomizu'

  get 'dashboard', to: 'dashboard#index'

  get 'feed' => 'top#feed'
  root 'dashboard#index', as: 'root'

  resources :projects
  resources :users

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/user.rb
# coding: utf-8
class User < ActiveRecord::Base
  # has_many :projects
  has_many :project_updates
  # belongs_to :project
  has_and_belongs_to_many :skills
  has_and_belongs_to_many :projects

  # OAuth 新規ユーザー作成
  # @param omniauthコールバックパラメータ
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid      = auth.uid
      user.name     = auth.info.name
      user.image    = auth.info.image
      user.save
    end
  end

  # 必要なスキルを更新
  # @param [Array] skill_names スキル名の配列
  # @return 増えたSKILLのID一覧
  def update_skill_ids_by_skill_names(skill_names)
    @before_skill_ids = skills.map(&:id)
    @after_skill_ids  = []

    if skill_names.present?
      skill_names.compact.uniq.reject(&:empty?).each do |skill_name|
        skill = Skill.find_by(name: skill_name)
        if skill.nil?
          skill = Skill.create(name: skill_name)
        end
        @after_skill_ids.push(skill.id)
      end
    end

    # 追加
    out = @after_skill_ids - @before_skill_ids
    out.each do |skill_id|
      skills << Skill.find(skill_id)
    end

    # 削除
    (@before_skill_ids - @after_skill_ids).each do |skill_id|
      skills.delete(skill_id)
    end

    return out
  end
end

app/controllers/users_controller.rb
# coding: utf-8

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  # GET /users
  # GET /users.json
  def index
    @skills = Skill.all
    skills = Skill.all.map { |skill| [skill.name, skill.id] }
    @options = skills.unshift(['指定なし', nil])

    if params[:skill_id].present?
      @users = User.joins(:skills).where(skills: { id: params[:skill_id] })
    else
      @users = User.all
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/1/edit
  def edit
    @from = params['from']
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      skills = Array(params.dig(:skill_names, :skill_ids)) + params.dig(:new_skills, :new_skills).split(' ')
      @user.update_skill_ids_by_skill_names(skills) if skills.size > 0
      if params[:from].to_s == 'dashboard'
        redirect_to '/dashboard', notice: 'プロフィールを更新しました。'
      else
        redirect_to @user, notice: 'プロフィールを更新しました。'
      end
    else
      render :edit
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
    @skills = Skill.all
    @my_skills = @user.skills.all.map { |k| k[:name] }
    @my_comments = ProjectUpdate.where(user_id: @user.id, freezing: [0, nil]).order(created_at: :desc).limit(10)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :description, :facebook_user_id, :receive_all)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def name_and_link(user)
    link_to(user.name, user_path(id: user.id))
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= hidden_field_tag :from, @from.to_s %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>入力に誤りがあります</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="user-edit">
    <div class="row">
      <div class="col-md-2">
        <%= t('dic.name')%>
      </div>
      <div class="input_text form-control">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2">
        <%= t('dic.self_intro')%>
      </div>
      <div class="input_text">
        <%= f.text_area :description, class: 'form-control', rows: 5 %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2">
        <%= t('dic.email')%><%= t('dic.not_public')%>
      </div>
      <div class="input_text">
        <%= f.text_field :email, :class => 'form-control' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2">
        <%= t('dic.receive_all') %>
      </div>
      <div class="input_text">
        <%= f.label(:receive_all) do %>
          <%= f.check_box(:receive_all, checked: !@user.receive_all.nil? && @user.receive_all) %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2">
        <%= t('dic.able_to')%>
      </div>
      <div class="col-md-2">
        <%= collection_check_boxes(:skill_names, :skill_ids, Skill.all, :name, :name) do |b| %>
          <%= b.label { b.check_box(checked: @my_skills.include?(b.text)) + b.text } %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2">
        <%= t '.new_skill'%>
      </div>
      <div class="input_text">
        <%= text_field :new_skills, :new_skills %>
      </div>
    </div>
  </div>
  <button type="submit" class="btn btn-default btn-primary btn2submit" aria-label="Left Align">
    <%= t('dic.update')%>
  </button>
<% end %>

app/views/users/edit.html.erb
<%= provide(:title, t('title.users.edit')) %>

<div class="content">
  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <%= render 'form' %>
  <% if @from == 'dashboard' %>
    <%= link_to dashboard_path do %>
      <button type="submit" class="btn btn-default mt20 btn2secondary" aria-label="Left Align">
        <%= t('dic.back')%>
      </button>
    <% end %>
  <% else %>
    <%= link_to @user do %>
      <button type="submit" class="btn btn-default mt20 btn2secondary" aria-label="Left Align">
        <%= t('dic.back')%>
      </button>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<%= provide(:title, t('title.users.index')) %>

<div class="content">
  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <div class="member_title"><%= t('.members') %></div>
  <div class="row">
    <div class="col-md-4">
      <%= form_tag users_path, :method => 'GET' do %>
        <%= select_tag 'skill_id', options_for_select(@options, :selected => params[:skill_id]), :class => 'form-control' %>
        <button class="btn btn-default user-search__button" type="submit"><%= t('.query')%></button>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="member_section clearfix">
      <% @users.each do |user| %>
        <div class="member_list clearfix">
          <div class="member"><%= image_tag(user.image) %></div>
          <div class="member_name"><%= name_and_link(user) %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= provide(:title, t('title.users.show', name: @user.name)) %>

<div class="content">
  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <div class="content_inner">
    <div class="content_header clearfix">
      <div class="member"><%= image_tag(@user.image) %></div>
      <div class="member_name"><%= link_to @user.name, "https://www.facebook.com/app_scoped_user_id/#{@user.uid}/" %></div>
    </div>
    <div class="content_box">
      <p class="mb20">
        <%= description_text(@user.description) %>
      </p>
    </div>

    <!-- メールアドレス(本人しか表示しない) -->
    <% if authorized? && @my_user.id == @user.id %>
      <% if @my_user.email.to_s == '' %>
        <div class="content_status">
          <div class="content_status_left"> <%= t('dic.email') %></div>
          <div class="content_status_right">
            <%= t('dic.recommend')%>
          </div>
        </div>
      <% else %>
        <div class="content_status">
          <div class="content_status_left"> <%= t('dic.email') %></div>
          <div class="content_status_right">
            <%= @my_user.email %>
          </div>
        </div>
      <% end %>
    <% end %>

    <!-- 参加中 -->
    <div class="content_status">
      <div class="content_status_left">参加中</div>
      <div class="content_status_right">
        <%  @user.projects.each do |project| %>
          <%= link_to( project.subject, project_url(id: project.id)) %>
          <% if project != @user.projects.last %>
            ,
          <% end %>
        <% end %>
      </div>
    </div>

    <!-- 作成した課題の数 -->
    <div class="content_property">
      <div class="content_property_left">作成した課題の数</div>
      <div class="content_property_right">
        <%= Project.where(user_id: @user.id).count %>
      </div>
    </div>

    <!-- 参加している課題の数 -->
    <div class="content_property">
      <div class="content_property_left">参加している課題の数</div>
      <div class="content_property_right">
        <%= @user.projects.count %>
      </div>
    </div>

    <!-- コメントの数 -->
    <div class="content_property">
      <div class="content_property_left">コメントした数</div>
      <div class="content_property_right">
        <%= @user.project_updates.count %>
      </div>
    </div>


    <!-- スキル一覧 -->
    <div class="content_skill clearfix">
      <div class="content_status_left">スキル</div>
      <div class="content_status_right">
        <% @user.skills.each do |s| %>
          <%= link_to users_path(skill_id: s.id) do %>
            <span class="skill_web"><%= s.name %></span>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="content_control clearfix">
    <!-- <div class="btn"><a href="#">投稿を削除する</a></div> -->
    <% if authorized? && @my_user.id == @user.id %>
      <div class="btn"><%= link_to t('.edit'), edit_user_path(@user) %></div>
    <% end %>
  </div>

  <!-- 最近のコメント -->
  <div class="content_status clearfix">
    <div class="content_status_left">直近コメント(10)</div>
    <div class="content_status_right">
      <% @my_comments.each do |comment| %>
        <p>
          <%= link_to comment.project.subject, project_path(comment.project.id, anchor: "comment-#{comment.id}") %> ( <%= time_ago_in_words comment.created_at %> )
        </p>
      <% end %>
    </div>
  </div>
</div>