config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/destroy'

  get 'auth/:provider/callback', to: 'sessions#create' # , via: 'get'
  get 'auth/failure', to: redirect('/') # , via: 'get'
  get 'signout', to: 'sessions#destroy', as: 'signout' #, via: 'get'

  resources :project_updates

  get 'top/help', as: 'help'

  get 'auth/logout', as: 'logout'

  post 'auth/signup_check', as: 'signup_check'

  post 'auth/login_check', as: 'login_check'

  get 'auth/signup'

  get 'top/index'

  get 'auth/login', as: 'login'

  get 'auth/signup', as: 'signup'

  get 'user/list', as: 'user_list'

  get 'user/detail/:user_id' => 'user#detail', as: 'user_detail'

  get 'user/edit/:user_id' => 'user#edit', as: 'user_edit'

  get 'project/detail/:project_id' => 'project#detail', as: 'project_detail'

  get 'project/edit', as: 'project_edit'

  get 'project/create', as: 'project_create'

  get 'projects/join/:id', to: 'projects#join'

  get 'projects/leave/:id', to: 'projects#leave'

  get 'projects/posts/:id', to: 'projects#kakikomizu'

  get 'dashboard', to: 'dashboard#index'

  get 'feed' => 'top#feed'
  root 'dashboard#index', as: 'root'

  resources :projects
  resources :users

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/project.rb
# coding: utf-8
class Project < ActiveRecord::Base
  attribute :images, ArrayType.new
  mount_uploaders :images, ImageUploader
  serialize :images, JSON
  validates :subject, presence: true
  has_many :project_updates
  belongs_to :user
  has_and_belongs_to_many :users
  has_and_belongs_to_many :skills
  belongs_to :stage
  belongs_to :project
  has_many   :projects

  scope :recent, -> { order(last_commented_at: 'desc') }

  scope :recruiting, -> { where.not(stage_id: 13) }

  scope :match_skills, lambda { |skill_ids|
    where.not(stage_id: 13)
         .includes(:skills)
         .where(skills: { id: skill_ids })
  }

  scope :original_order, lambda { |ids|
    if Array(ids).empty?
      where(id: [])
    else
      where(id: ids).order("field(id, #{ids.join(',')})")
    end
  }

  def self.comment_ranking(before)
    Project
      .joins(:project_updates)
      .where(
        project_updates: {
          created_at: Time.now.ago(30.years)...before
        }
      )
      .group('project_updates.project_id')
      .order('count_project_updates_project_id desc')
      .count('project_updates.project_id')
  end

  # プロジェクトを編集可能なユーザーかどうか
  # @param [Integer] user_id
  # @return [Boolean]
  def editable_user_id?(user_id)
    if user_id == self.user_id
      return true
    else
      return false
    end
  end

  # 必要なスキルを更新
  # @param [Array] skill_names スキル名の配列
  # @return [Boolean]
  def update_skill_ids_by_skill_names(skill_names)
    @before_skill_ids = skills.map(&:id)
    @after_skill_ids  = []
    skill_names.compact.uniq.reject(&:empty?).each do |skill_name|
      skill = Skill.find_by(name: skill_name)
      if skill.nil?
        skill = Skill.create(name: skill_name)
      end
      @after_skill_ids.push(skill.id)
    end

    # 追加
    (@after_skill_ids - @before_skill_ids).each do |skill_id|
      skills << Skill.find(skill_id)
    end

    # 削除
    (@before_skill_ids - @after_skill_ids).each do |skill_id|
      skills.delete(skill_id)
    end
  end

  # メールを送るユーザーを取得
  def send_mail_users
    send_users = users
    me = user

    # 自分がいない場合には含める
    if send_users.select { |u| u['user_id'] == me['user_id'] }.empty?
      send_users.push me
    end

    # すべてを受け取るユーザーを追加
    User.where(receive_all: 1).pluck(:email).compact each do |u|
      send_users.push u
    end
    send_users
  end

  def send_mail_addresses
    send_targets = users.pluck(:email).compact
    me = user.email

    # 自分がいない場合には含める
    if send_targets.include?(me)
      send_targets.push me
    end

    # すべてを受け取るユーザーを追加
    User.where(receive_all: 1).pluck(:email).compact.each do |u|
      send_targets.push u
    end
    send_targets.uniq
  end

  def send_mail_skill_matched_users
    Users.find
  end
end

app/models/user.rb
# coding: utf-8
class User < ActiveRecord::Base
  # has_many :projects
  has_many :project_updates
  # belongs_to :project
  has_and_belongs_to_many :skills
  has_and_belongs_to_many :projects

  # OAuth 新規ユーザー作成
  # @param omniauthコールバックパラメータ
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid      = auth.uid
      user.name     = auth.info.name
      user.image    = auth.info.image
      user.save
    end
  end

  # 必要なスキルを更新
  # @param [Array] skill_names スキル名の配列
  # @return 増えたSKILLのID一覧
  def update_skill_ids_by_skill_names(skill_names)
    @before_skill_ids = skills.map(&:id)
    @after_skill_ids  = []

    if skill_names.present?
      skill_names.compact.uniq.reject(&:empty?).each do |skill_name|
        skill = Skill.find_by(name: skill_name)
        if skill.nil?
          skill = Skill.create(name: skill_name)
        end
        @after_skill_ids.push(skill.id)
      end
    end

    # 追加
    out = @after_skill_ids - @before_skill_ids
    out.each do |skill_id|
      skills << Skill.find(skill_id)
    end

    # 削除
    (@before_skill_ids - @after_skill_ids).each do |skill_id|
      skills.delete(skill_id)
    end

    return out
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  include SnsPublisher
  before_action :set_project, only: [:show, :edit, :update, :destroy, :join, :leave]

  # GET /projects
  def index
    type = params[:type]
    page = params[:page]
    query = Project.page(page).includes(
      :project_updates,
      :user,
      :project,
      :projects,
      :users,
      :skills,
      :stage
    )
    if type == 'recent'
      @list_type = I18n.t('dic.project_recent')
      @projects = query.order(last_commented_at: :desc)
    elsif type == 'hotrank'
      @list_type = I18n.t('dic.project_hot')
      rank = Project.comment_ranking(default_duration)
      @projects = query.original_order(rank.keys)
    elsif type == 'match'
      @projects = []
      unless @my_user.nil?
        @list_type = I18n.t('dic.project_match_mine')
        @projects = query.match_skills(@my_user.skill_ids)
      end
    else
      @list_type = I18n.t('dic.project_all')
      @projects = query.order(:id)
    end
  end

  # GET /projects/1
  def show
    @project_rss_url = request.fullpath + '.rss'
    add_rss_urls(@project.subject, @project_rss_url)
    respond_to do |format|
      format.html
      format.rss { render layout: false }
    end
  end

  # GET /projects/new
  def new
    @project   = Project.new
    @skills    = Skill.all
    @users     = User.all
    @my_skills = []
    @parent_project = nil
    @parent_project = Project.find(params[:parent_id]) unless params[:parent_id].nil?
    @from = params[:from]
  end

  # GET /projects/1/edit
  def edit
    @stages = Stage.all
    @users  = User.all
  end

  # POST /projects
  def create
    @project = Project.new(project_params)
    @project.user_id = @my_user.id
    @project.last_commented_at = Time.now
    skills = Array(params.dig(:skill_names, :skill_ids)) + params.dig(:new_skills, :new_skills).split(' ')
    @project.update_skill_ids_by_skill_names(skills) unless skills.empty?

    # 作成時自分を参加させる
    @project.users.push(@my_user)

    if @project.save
      # mail to created
      @project.send_mail_addresses.each do |m|
        ProjectMailer.tell_create(m, @project).deliver_later unless m == ''
      end

      project_publish_to_sns_page(
        "#{@my_user.name} さんが課題 #{@project.subject} を作成しました。",
        @project,
        @my_user
      )

      # mail to skill matched
      User.joins(:skills).where(skills: { id: @project.skills }).pluck(:email).compact.each do |m|
        ProjectMailer.tell_skill_match(m, @project, true).deliver_later unless m == ''
      end

      redirect_target = params[:from].nil? ? @project : '/dashboard'
      redirect_to redirect_target, notice: I18n.t('projects.banner.created')
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    param_cache = project_params
    unless param_cache[:images].nil?
      images = @project.images
      images += param_cache[:images]
      param_cache[:images] = images
    end
    before_skills = @project.skills.map(&:id)
    if @project.update(param_cache)

      if params[:project][:remove_images].to_i > 0
        remain_images = @project.images
        remain_images.each_with_index do |_v, i|
          _deleted_image = remain_images.delete_at(i)
          # _deleted_image.try(:remove!)
        end
        @project.images = remain_images
        @project.update!(images: remain_images)
      end

      skills = Array(params.dig(:skill_names, :skill_ids)) + params.dig(:new_skills, :new_skills).split(' ')
      @project.update_skill_ids_by_skill_names(skills) unless skills.empty?

      current_skills = @project.skills.map(&:id)
      fue = current_skills - before_skills

      project_publish_to_sns_page(
        "#{@my_user.name} さんが課題 #{@project.subject} を更新しました。",
        @project,
        @my_user
      )

      # mail to skill matched
      User.joins(:skills).where(skills: { id: fue }).pluck(:email).compact.each do |m|
        ProjectMailer.tell_skill_match(m, @project).deliver_later unless m == ''
      end

      redirect_to @project, notice: I18n.t('projects.banner.updated')
    else
      render :edit
    end
  end

  # GET /projects/add
  # メンバー追加
  def add
  end

  # Join Project
  def join
    if @my_user.nil?
      redirect_to @project, notice: I18n.t('projects.banner.cannot')
    else
      @project.users << @my_user
      redirect_to @project, notice: I18n.t('projects.banner.joined')
    end
  end

  # Leave Project
  def leave
    if @my_user.nil?
      redirect_to @project, notice: I18n.t('projects.banner.cannot')
    else
      begin
        ProjectUpdate.new(
          project_id:  @project.id,
          description: "#{@my_user.name} さんは課題 #{@project.subject} への参加を辞めました。",
          freezing:    true,
          user_id:     @my_user.id
        ).save

        @project.users.delete(@my_user)
        redirect_to @project, notice: I18n.t('projects.banner.leaved')
      rescue => e
        logger.debug(e.to_s)
        redirect_to @project, notice: I18n.t('projects.banner.cannot')
      end
    end
  end

  # POST /projects/add_member
  def add_member
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    include_target = [
      { project_updates: { project_update_histories: :user } },
      :user,
      :project,
      :projects,
      :users,
      :skills,
      :stage
    ]
    @project = Project.includes(*include_target)
                      .find(params[:id])
    @skills   = Skill.all
    @joinners = Project.find(params[:id]).users
    @my_skills = @project.skills.all.map { |k| k[:name] }
    if session[:user_id]
      @joined = !Project.find(params[:id]).users.find_by(id: session[:user_id]).nil?
    else
      @joined = false
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:user_id, :stage_id, :subject, :description, :user_url, :development_url, :project_id, { images: [] }, :remove_images)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project, html: { multipart: true }) do |f| %>
  <%= hidden_field_tag :from, @from.to_s %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% @project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="project-detail__define">
    <!-- タイトル -->
    <div class="row">
      <% if @parent_project.nil? %>
      <% else %>
        <%= f.hidden_field :project_id, value: @parent_project.id %>
      <% end %>
      <div class="col-md-2">
        <%= t 'dic.title' %>
      </div>
      <div class="input_text">
        <%= f.text_field :subject, placeholder: t('dic.ex_subject') %>
      </div>
    </div>

    <!-- URL -->
    <div class="row">
      <div class="col-md-2">
        URL
      </div>
      <div class="input_text">
        <%= f.url_field :user_url, class: 'form-control', placeholder: t('dic.ex_url') %>
      </div>
    </div>

    <!-- 開発URL -->
    <div class="row">
      <div class="col-md-2">
        <%= t '.dev_url' %>
      </div>
      <div class="input_text">
        <p>
          <%= f.url_field :development_url, class: 'form-control', placeholder: t('dic.ex_devurl') %>
        </p>
        <p>
          <%= t('.recommend_dev_url')%>
        </p>
      </div>
    </div>

    <!-- 詳細 -->
    <div class="row">
      <div class="col-md-2">
        <%= t 'dic.detail' %>
      </div>
      <div class="input_text">
        <%= f.text_area :description, class: 'form-control', rows: 5, placeholder: t('dic.ex_description') %>
      </div>
    </div>

    <!-- 画像一覧(編集時には表示しない) -->
    <% if (params[:action] == 'edit') %>
      <div class="row">
        <div class="col-md-2">
          画像一覧
        </div>
        <div class="col-md-2">
          <% if @project.images.size == 0 %>
            なし
          <% else %>
            <%= f.label "remove_images" do %>
              <%= f.check_box(:remove_images) + "添付画像を全て削除する" %>
            <% end %>
            <% @project.images.each_with_index do |img, index| %>
              <div class="content_box">
                <p class="image_all">
                  <%= image_tag(img.url) %>
                </p>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>

    <!-- 画像投稿ボタン -->
    <div class="row">
      <div class="col-md-2">
        画像添付
      </div>
      <div class="col-md-2">
        <%= f.file_field :images, multiple: true %>
      </div>
    </div>


    <!-- 必要なスキル -->
    <div class="row">
      <div class="col-md-2">
        <%= t '.skill'%>
      </div>
      <div class="col-md-2">
        <p>
        <%= collection_check_boxes(:skill_names, :skill_ids, Skill.all, :name, :name) do |b| %>
          <%= b.label { b.check_box(checked: @my_skills.include?(b.text)) + b.text } %>
        <% end %>
        </p>
        <p>
          <%= t('.recommend_skill')%>
        </p>
      </div>
    </div>

    <!-- 必要なスキル(まだ作られていない) -->
    <div class="row">
      <div class="col-md-2">
        <%= t '.new_skill'%>
      </div>
      <div class="input_text">
        <%= text_field :new_skills, :new_skills, placeholder: t('dic.ex_skills') %>
      </div>
    </div>
    <% if (params[:action] == 'edit') then %>
      <div class="row">
        <div class="col-md-2">
          <%= t 'dic.status' %> <%= link_to t('dic.detail'), ENV['LINK_ABOUT_PROJECT_STATUS'], target: '_blank' %>
        </div>
        <div class="col-md-10">
          <div class="form-inline mt10">
            <%= f.select :stage_id, @stages.map{ |stage| [stage.name, stage.id] }, :selected => @project.stage_id %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <!-- 利用規約確認ボタン -->
  <% if (params[:action] == 'edit') then %>
    <div>
      <button type="submit" class="btn btn-default btn-primary" aria-label="Left Align">
        <%= t 'dic.do_edit' %>
      </button>
    </div>
  <% else %>
    <div>
      <label for="agree_message_check">
        <input type="checkbox" id="agree_message_check" name="agreecheck" value="1">
        <%= link_to t('dic.user_term'), ENV['LINK_USER_TERMS'], target: '_blank' %><%= t('dic.user_term_check')%>
      </label>
    </div>
    <div>
      <button type="submit" disabled id="need_agree_button" class="btn btn-default btn-primary btn2submit" aria-label="Left Align">
        <%= t 'dic.do_create' %>
      </button>
    </div>
  <% end %>
<% end %>

app/views/projects/edit.html.erb
<%= provide(:title, t('title.projects.edit', name: @project.subject)) %>

<div class="content">
  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <%= render 'form' %>
  <%= link_to @project do %>
    <button type="submit" class="btn btn-default mt20" aria-label="Left Align">
      <%= t('dic.back')%>
    </button>
  <% end %>
</div>

app/views/projects/index.html.erb
<%= provide(:title, t('title.projects.index')) %>

<div class="content">
  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <div class="list_title"><%= @list_type %></div>

  <% @projects.each do |project| %>
    <%= render 'shared/project', project: project %>
  <% end %>
  <div>
    <%= paginate @projects %>
  </div>
</div>

app/views/projects/new.html.erb
<%= provide(:title, t('title.projects.new')) %>

<div class="content">
  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <div class="project-detail__define">
    <% unless @parent_project.nil? %>
      <div class="row">
        <div class="col-md-2">
          <%= t 'dic.parent_project' %>
        </div>
        <div class="input_text">
          <%= @parent_project.subject %>
        </div>
      </div>
    <% end %>
  </div>
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<%= provide(:title, t('title.projects.show', name: @project.subject)) %>
<% set_meta_tags og: { title: @project.subject, description: @project.description }  %>
<div class="content">
  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <div class="content_inner">
    <div class="content_header clearfix">
      <div class="content_title"><%= link_to(@project.subject, project_path(id: @project.id)) %></div>
      <div class="content_member">
        <%= link_to (image_tag @project.user.image, alt: @project.user.name, title: @project.user.name), user_path(id: @project.user.id) %>
      </div>
      <div class="content_time">
        <%= name_and_link(@project.user) %><% t('dic.title') %><br/>
        <%= created_at_ago(@project) %> <% t('dic.posted_on') %>
      </div>
    </div>

    <!-- Description -->
    <div class="content_box">
      <%= description_text(@project.description) %>
    </div>

    <!-- Image -->
    <% @project.images.each_with_index do |img, index| %>
      <div class="content_box">
        <p class="image_all">
          <%= image_tag(img.url) %>
        </p>
      </div>
    <% end %>

    <!-- SNS SHARE -->
    <div class="content_sns_share clearfix">
      <div class="content_sns_share_left">
        <%= t('dic.sns')%>
      </div>
      <div class="content_sns_share_right">
        <%= facebook_share_btn(project_path(id: @project.id)) %>
      </div>
    </div>

    <!-- URL -->
    <div class="content_development_url clearfix">
      <div class="content_development_url_left"><%= t('dic.url')  %></div>
      <div class="content_development_url_right">
        <%= link_to_if @project.user_url.present?, @project.user_url, @project.user_url  do %>
          <span><%= t('dic.url') %>はありません</span>
        <% end %>
      </div>
    </div>

    <!-- 開発URL -->
    <div class="content_development_url clearfix">
      <div class="content_development_url_left"><%= t('dic.dev_url')  %></div>
      <div class="content_development_url_right">
        <%= link_to_if @project.development_url.present?, @project.development_url, @project.development_url do %>
          <span><%= t('dic.dev_url') %>はありません</span>
        <% end %>
       </div>
    </div>

    <!-- ステータス -->
    <div class="content_status clearfix">
      <div class="content_status_left"><%= t('dic.status') %></div>
      <div class="content_status_right"><%= link_to @project.stage.name, ENV['LINK_ABOUT_PROJECT_STATUS'], target: '_blank' %></div>
    </div>

    <!-- 元の課題 -->
    <div class="content_parent_project clearfix">
      <div class="content_parent_project_left"><%= t('dic.parent_project') %></div>
      <div class="content_parent_project_right">
        <% unless @project.project.nil? %>
          <%= link_to @project.project.subject, project_path(id: @project.project.id) %>
        <% end %>
      </div>
    </div>

    <!-- 関連課題(子) -->
    <div class="content_child_project clearfix">
      <div class="content_child_project_left"><%= t('dic.child_project') %></div>
      <div class="content_child_project_right">
        <% @project.projects.each do |p| %>
          <%= link_to p.subject, project_path(id: p.id) %> <br/>
        <% end %>
      </div>
    </div>

    <!-- 募集スキル -->
    <div class="content_skill clearfix">
      <div class="content_skill_left"><%= t('dic.wantskill') %></div>
      <div class="content_skill_right">
        <% @project.skills.each do |s| %>
          <%= link_to users_path(skill_id: s.id) do %>
            <span class="skill_web"><%= s.name %></span>
          <% end %>
        <% end %>
      </div>
    </div>

    <!-- メンバーリスト -->
    <div class="content_join clearfix">
      <div class="content_join_left"><%= t('dic.member_list') %></div>
      <div class="content_join_right">
        <% @project.users.each do |user| %>
          <span class="join_thum"><%= link_to image_tag(user.image, alt: user.name, title: user.name), user_path(id: user.id) %></span>
        <% end %>
      </div>
    </div>
  </div>

  <!-- 操作ボタン -->
  <div class="content_control clearfix">
    <!-- <div class="btn"><a href="#">投稿を削除する</a></div> -->
    <% if authorized? %>
      <div class="btn2" id="write_comment">
        <a href="#">
          <%= t('.write_comment') %>
        </a>
      </div>
      <div class="btn">
        <%= link_to t('dic.post_belong_project'), new_project_path(parent_id: @project.id) %>
      </div>
      <% if @project.user.id == @my_user.id %>
        <div class="btn"><%= link_to t('.edit'), edit_project_path, class: "btn btn-default btn-primary" %></div>
      <% end %>
      <% if @joined %>
        <% if @project.user.id != @my_user.id %>
          <div class="btn">
            <%= link_to( t('projects.show.leave'), {controller: :projects, action: :leave, id: @project.id}) %>
          </div>
        <% end %>
      <% else %>
        <div class="btn">
            <%= link_to( t('projects.show.join'), {controller: :projects, action: :join, id: @project.id}) %>
          </div>
      <% end %>
    <% else %>
      <div class="btn">
        <%= link_to( t('projects.show.login'), '/auth/google_oauth2', id: 'sign_in', method: :post) %>
      </div>
        ( <%= t('projects.show.login_recomendation') %> )
    <% end %>
  </div>

  <!-- コメント記入欄(最初は非表示) -->
  <% if authorized? %>
    <div class="comment clearfix" id="add_comment" style="display:none;">
      <div class="comment_thum">
        <%= link_to image_tag(@my_user.image, alt: @my_user.name, title: @my_user.name), user_path(id: @my_user.id) %>
      </div>
      <div class="comment_text input_text">
        <%= form_for(ProjectUpdate.new) do |f| %>
          <%= f.hidden_field :project_id, value: @project.id %>
          <%= f.text_area :description, class: 'form-control', placeholder: t('dic.ex_comment'), rows: 5 %>
          <%= f.file_field :comment_image %>
          <button type="submit" class="btn2submit" align="right">
            <%= t 'dic.do_comment' %>
          </button>
        <% end %>
      </div>
    </div>
  <% end %>

  <!-- コメント一覧(古いのが下、新しいのは上) -->
  <% @project.project_updates.includes(:user).reverse.each do |update| %>
    <div class="comment clearfix" id="comment-<%=update.id%>">
      <div class="comment_thum">
        <%= link_to image_tag(update.user.image, alt: update.user.name, title: update.user.name), user_path(id: update.user.id) %>
      </div>
      <div class="comment_text">
        <p><%= description_text(update.description) %></p>
        <p class="image_all">
          <%= image_tag(update.comment_image.url) if update.comment_image? %>
        </p>
        <p class="comment_author">
          <%= created_at_ago(update, project_path(id: @project.id, anchor: "comment-#{update.id}"))%> <%= t 'dic.posted_on' %>
          <% if authorized? && update.freezing.to_s != 'true' && (update.user_id == @my_user.id || @project.user_id == @my_user.id) %>
            <%= link_to t('dic.do_edit'), edit_project_update_path(update, project_id: @project.id) %> -
            <%= link_to t('dic.do_delete'), project_update_path(update, project_id: @project.id), method: :delete %>
          <% end %>
          <br/>
          <% update.project_update_histories.sort { |a, b| a.created_at <=> b.created_at}.each do |history| %>
            <%= history.user.name %> <%= t('dic.is') %> <%= created_at_ago(history) %> <%= t('dic.edited_on') %> <br/>
          <% end %>
        </p>
      </div>
    </div>
  <% end %>

  <div class="content_control clearfix">
    <%= link_to( image_tag('Feed-icon.svg', size: '20x20', style: 'vertical-align:middle;'), @project_rss_url) %> この課題の更新を RSS で確認することもできます。
  </div>

</div>