config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/destroy'

  get 'auth/:provider/callback', to: 'sessions#create' # , via: 'get'
  get 'auth/failure', to: redirect('/') # , via: 'get'
  get 'signout', to: 'sessions#destroy', as: 'signout' #, via: 'get'

  resources :project_updates

  get 'top/help', as: 'help'

  get 'auth/logout', as: 'logout'

  post 'auth/signup_check', as: 'signup_check'

  post 'auth/login_check', as: 'login_check'

  get 'auth/signup'

  get 'top/index'

  get 'auth/login', as: 'login'

  get 'auth/signup', as: 'signup'

  get 'user/list', as: 'user_list'

  get 'user/detail/:user_id' => 'user#detail', as: 'user_detail'

  get 'user/edit/:user_id' => 'user#edit', as: 'user_edit'

  get 'project/detail/:project_id' => 'project#detail', as: 'project_detail'

  get 'project/edit', as: 'project_edit'

  get 'project/create', as: 'project_create'

  get 'projects/join/:id', to: 'projects#join'

  get 'projects/leave/:id', to: 'projects#leave'

  get 'projects/posts/:id', to: 'projects#kakikomizu'

  get 'dashboard', to: 'dashboard#index'

  get 'feed' => 'top#feed'
  root 'dashboard#index', as: 'root'

  resources :projects
  resources :users

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja" class="build-menu-close">
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,user-scalable=no,maximum-scale=1,initial-scale=1" />
    <% unless Array(@rss_urls).length == 0 %>
      <% @rss_urls.each do |rss| %>
        <link rel="alternate" type="application/rss+xml" title="<%=rss[:name]%>" href="<%=rss[:url]%>" />
      <% end %>
    <% end %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <%= display_meta_tags default_meta_tags %>
    <%= yield :twitter_card %>
    <%= %>
  </head>
  <body>
    <div class="all">
      <header id="pc_header">
        <section class="container clearfix">
          <div class="header_left">
            <h1><%= link_to( "Code for Kanazawa", root_path ) %></h1>
          </div>
          <div class="header_center">
            <h2><%= link_to( image_tag('matsu/logo.png'), root_path) %></h2>
          </div>
          <div class="header_right">
            <div class="header_nav">
              <ul id="first_ul" class="drop_nav">
                <li class="nav-child">
                  <a href="#"><%= image_tag('matsu/header_item3.png') %></a>
                  <!--プルダウンメニュー-->
                  <ul class="sub_nav">
                    <% if authorized? %>
                      <li><%= link_to( t('dic.dashboard'), dashboard_path) %></li>
                      <li><%= link_to( t('dic.mypage'), user_path(id: @my_user.id)) %></li>
                      <li><%= link_to( t('dic.logout'), signout_path, id: 'sign_out') %></li>
                      <li><%= link_to( t('dic.post_project_do'), new_project_path) %></li>
                    <% else %>
                      <li><%= link_to( t('dic.login'), '/auth/google_oauth2', id: 'sign_in', method: :post) %></li>
                    <% end %>
                    <li><%= link_to( t('dic.member'), users_path) %></li>
                    <li><%= link_to( t('dic.privacy_policy'), ENV['LINK_PRIVACY_POLICY']) %></li>
                    <li><%= link_to( t('dic.terms_of_service'), ENV['LINK_USER_TERMS']) %></li>
                  </ul>
                  <!--プルダウンメニューここまで-->
                </li>
              </ul>
            </div>
            <% if authorized? %>
              <div class="user_name"><%= @my_user.name %></div>
              <div class="login_after">
                <span class="login_thum"><%= image_tag @my_user.image %></span>
              </div>
              <div class="post_content">
                <%= link_to( image_tag('matsu/header_item1.png'), new_project_path) %>
              </div>
            <% else %>
              <div class="login">
                <%= link_to( image_tag('matsu/header_item2.png'), '/auth/google_oauth2', id: 'sign_in', method: :post) %>
              </div>
            <% end %>
          </div>
        </section>
      </header>
      <!--スマートフォン用ヘッダーここから-->
      <header id="sp_header">
        <section class="container clearfix">
          <div class="sp_header_title"><%= link_to( "Code for Kanazawa", '/' ) %></div>
          <div class="sp_header_logo">
            <h2><%= link_to( image_tag('matsu/logo.png'), '/') %></h2>
          </div>
          <div class="sp_header_nav">
            <nav id="mobile-bar"></nav>
            <nav id="sp_nav">
              <ul>
                <% if authorized? %>
                  <li class="li_sub">
                    <%= link_to t('dic.post_project_do'), new_project_path , class: "btn btn-default btn-primary" %>

                  </li>
                  <li class="li_sub">
                    <%= link_to( t('dic.dashboard'), dashboard_path) %>
                  </li>
                  <li class="li_sub">
                    <%= link_to( t('dic.mypage'), user_path(id: @my_user.id)) %>
                  </li>
                  <li class="li_sub">
                    <%= link_to( t('dic.logout'), signout_path, id: 'sign_out') %>
                  </li>
                <% else %>
                  <li class="li_sub"><%= link_to( t('dic.login'), '/auth/google_oauth2', id: 'sign_in', method: :post) %></li>
                <% end %>
                <li class="li_sub"><%= link_to( t('dic.member'), users_path) %></li>               <li><%= link_to( t('dic.privacy_policy'), ENV['LINK_PRIVACY_POLICY']) %></li>
                <li><%= link_to( t('dic.terms_of_service'), ENV['LINK_USER_TERMS']) %></li>
              </ul>
            </nav>
          </div>
        </section>
      </header>
      <!--スマートフォン用ヘッダーここまで-->
      <!--コンテンツ-->
      <div id="wrapper">
        <article>
          <div class="container clearfix">
            <%= yield %>
            <div class="menu">
              <div class="clearfix">
                <section class="menu_search">
                  <h1><%= t('dic.find_project') %></h1>
                </section>
                <div class="menu01">
                  <%= link_to t('dic.project_recent'), projects_path(type: 'recent', order: 'desc') %>
                </div>
                <div class="menu02">
                  <%= @projects_recent_count %>
                </div>

                <div class="menu01">
                  <%= link_to t('dic.project_hot'), projects_path(type: 'hotrank') %>
                </div>
                <div class="menu02">
                  <%= @projects_hot_rank_count %>
                </div>

                <% if authorized? %>
                  <div class="menu01">
                    <%= link_to t('dic.project_match_mine'), projects_path(type: 'match') %>
                  </div>
                  <div class="menu02">
                    <%= @projects_match %>
                  </div>
                <% end %>

                <div class="menu01">
                  <%= link_to t('dic.project_all'), projects_path %>
                </div>
                <div class="menu02">
                  <%= @projects_all_count %>
                </div>
              </div>
              <% if authorized? %>
                <div class="menu_post">
                  <%= link_to image_tag('matsu/menu_item01.png'), new_project_path %>
                </div>
              <% end %>

              <div class="clearfix">
                <section class="menu_user_search">
                  <h1><%= t('dic.member_search') %></h1>
                </section>
                <div class="menu01">
                  <%= link_to( t('dic.member_all'), users_path) %>
                </div>
                <div class="menu02">
                  <%= User.all.count %>
                </div>

                <% Skill.skill_members.each do |s| %>
                  <% if s.users.count > 0 %>
                    <div class="menu01">
                      <%= link_to( s.name, users_path(skill_id: s.id)) %>
                    </div>
                    <div class="menu02">
                      <%= s.users.count %>
                    </div>
                  <% end %>
                <% end %>
              </div>

              <section class="menu_news">
                <h1><%= t('dic.admin_msg') %></h1>
                <% @app_infors.each do |info| %>
                  <dl>
                    <dt><%= info.release %></dt>
                    <dd><%= info.description %></dd>
                  </dl>
                <% end %>
              </section>
            </div>
          </div>
        </article>
      </div>
      <!--コンテンツ-->

      <footer>
        <div class="container clearfix">
        </div>
      </footer>
      <div class="copyright">
        プライバシーポリシー copyright(c) 2016 Ha4go All Right Reserved.
      </div>
    </div>

    <%= javascript_include_tag :application, :jquery, :bootstrap, :jquery_ujs, 'matsu/jquery.mobile-menu' %>
    <%= render 'shared/facebook' %>
    <%= render 'shared/twitter' %>
    <%= analytics_init if Rails.env.production? %>
    <script>
     $(function(){
       $("body").mobile_menu({
         menu: ['#sp_nav ul'],
         menu_width: 260,
         prepend_button_to: '#mobile-bar',
         button_content: '<img src="<%= asset_path "matsu/nav.gif" %>" width="20px">'
       });
     });
    </script>
  </body>
</html>